language: node_js
node_js:
  - "5.0"
  - "4.2"
  - "4.1"
  - "4.0"
before_install:
  - "sudo add-apt-repository -y ppa:rethinkdb/ppa"
  - "sudo apt-get update"
  - "sudo apt-get install -y rethinkdb"
before_script:
  - "rethinkdb"